name: aegis-host
base: core22
version: '0.1.0'
summary: Aegis Http HTTP GPG Daemon
description: |
  Aegis Http Native Messaging host to bridge browser extension and GPG.

grade: stable
confinement: classic

parts:
  aegis-host:
    plugin: rust
    source: .

apps:
  aegis-host:
    command: bin/aegis-host
